# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "jekyll", ENV["JEKYLL_VERSION"] if ENV["JEKYLL_VERSION"]
gem "kramdown-parser-gfm" if ENV["JEKYLL_VERSION"] == "~> 3.9"
gem 'wdm', '>= 0.1.0'
gem "webrick", "~> 1.7"
gem "github-pages", "~> 225", group: :jekyll_plugins
gem "jekyll-admin", group: :jekyll_plugins
gem "jekyll-seo-tag"
gem 'jekyll-scholar', group: :jekyll_plugins
